export const FONT = "'DM Sans', 'Segoe UI', sans-serif";

export const S = {
  page: { fontFamily: FONT },
  topRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '24px',
  },
  title: { fontSize: '20px', fontWeight: 900, color: '#0f172a', letterSpacing: '-0.5px' },
  subtitle: { fontSize: '13px', color: '#94a3b8', marginTop: '3px' },
  statsRow: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4,1fr)',
    gap: '14px',
    marginBottom: '24px',
  },
  statBox: {
    background: '#fff',
    borderRadius: '12px',
    padding: '18px 20px',
    border: '1px solid #f1f5f9',
    boxShadow: '0 1px 4px rgba(0,0,0,0.03)',
  },
  statNum: (color) => ({ fontSize: '28px', fontWeight: 900, color, lineHeight: 1 }),
  statLbl: { fontSize: '12px', color: '#94a3b8', fontWeight: 600, marginTop: '4px' },
  searchBar: {
    background: '#fff',
    border: '1.5px solid #e2e8f0',
    borderRadius: '10px',
    padding: '10px 16px',
    fontSize: '14px',
    width: '280px',
    outline: 'none',
    fontFamily: FONT,
    color: '#0f172a',
  },
  table: {
    background: '#fff',
    borderRadius: '16px',
    border: '1px solid #f1f5f9',
    overflow: 'hidden',
    boxShadow: '0 1px 4px rgba(0,0,0,0.04)',
  },
  thead: { background: '#f8fafc', borderBottom: '1px solid #f1f5f9' },
  th: {
    padding: '11px 18px',
    fontSize: '11px',
    fontWeight: 800,
    color: '#94a3b8',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    textAlign: 'left',
  },
  tr: (hover) => ({
    borderBottom: '1px solid #f8fafc',
    background: hover ? '#fafbfc' : '#fff',
    transition: 'background 0.15s',
    cursor: 'pointer',
  }),
  td: { padding: '14px 18px', fontSize: '13px', color: '#374151', verticalAlign: 'middle' },
  badge: (passed) => ({
    padding: '2px 10px',
    borderRadius: '20px',
    fontSize: '11px',
    fontWeight: 700,
    background: passed ? '#ecfdf5' : '#fef2f2',
    color: passed ? '#059669' : '#ef4444',
  }),
  expandRow: { background: '#f8fafc', borderBottom: '1px solid #f1f5f9' },
  attemptTable: { width: '100%', borderCollapse: 'collapse', fontSize: '12px' },
  attemptTh: {
    padding: '8px 12px',
    color: '#94a3b8',
    fontWeight: 700,
    textAlign: 'left',
    fontSize: '11px',
    textTransform: 'uppercase',
  },
  attemptTd: { padding: '10px 12px', color: '#475569', borderTop: '1px solid #f1f5f9' },
  progressBar: (pct, passed) => ({
    height: '6px',
    borderRadius: '3px',
    width: '60px',
    background: '#f1f5f9',
    overflow: 'hidden',
    position: 'relative',
    display: 'inline-block',
    verticalAlign: 'middle',
    marginRight: '6px',
  }),
  progressFill: (pct, passed) => ({
    display: 'block',
    height: '100%',
    borderRadius: '3px',
    width: `${Math.min(100, Number(pct) || 0)}%`,
    background: passed ? '#10b981' : '#ef4444',
  }),
  emptyState: { padding: '64px', textAlign: 'center' },
  emptyIcon: { fontSize: '40px', marginBottom: '12px' },
  emptyText: { color: '#94a3b8', fontSize: '14px' },
};
