export const FONT = "'DM Sans', 'Segoe UI', sans-serif";
export const S = {
  page: { fontFamily: FONT },
  // Header card
  headerCard: {
    background: '#fff',
    borderRadius: '16px',
    border: '1px solid #f1f5f9',
    boxShadow: '0 1px 4px rgba(0,0,0,0.04)',
    padding: '28px',
    marginBottom: '20px',
  },
  headerTop: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '20px',
  },
  examTitle: { fontSize: '22px', fontWeight: 900, color: '#0f172a', letterSpacing: '-0.5px' },
  examDesc: { fontSize: '14px', color: '#94a3b8', marginTop: '5px', lineHeight: 1.5 },
  headerActions: { display: 'flex', gap: '10px', alignItems: 'center' },
  publishBtn: (published) => ({
    padding: '10px 20px',
    borderRadius: '10px',
    fontSize: '13px',
    fontWeight: 700,
    background: published ? '#f1f5f9' : 'linear-gradient(135deg, #10b981, #059669)',
    color: published ? '#64748b' : '#fff',
    border: published ? '1px solid #e2e8f0' : 'none',
    cursor: published ? 'not-allowed' : 'pointer',
    boxShadow: published ? 'none' : '0 2px 8px rgba(16,185,129,0.35)',
    fontFamily: FONT,
  }),
  backBtn: {
    padding: '10px 16px',
    borderRadius: '10px',
    fontSize: '13px',
    fontWeight: 700,
    background: '#f8fafc',
    border: '1px solid #e2e8f0',
    color: '#64748b',
    cursor: 'pointer',
    fontFamily: FONT,
  },
  metaRow: { display: 'flex', gap: '12px', flexWrap: 'wrap' },
  metaChip: (color, bg) => ({
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    padding: '5px 12px',
    borderRadius: '20px',
    fontSize: '12px',
    fontWeight: 700,
    background: bg,
    color: color,
  }),
  statsDot: (color) => ({ width: '6px', height: '6px', borderRadius: '50%', background: color }),

  // Stats row
  statsRow: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4,1fr)',
    gap: '12px',
    marginBottom: '20px',
  },
  statBox: {
    background: '#fff',
    borderRadius: '12px',
    padding: '16px 20px',
    border: '1px solid #f1f5f9',
    boxShadow: '0 1px 4px rgba(0,0,0,0.03)',
  },
  statNum: {
    fontSize: '28px',
    fontWeight: 900,
    color: '#0f172a',
    letterSpacing: '-0.5px',
    lineHeight: 1,
  },
  statLbl: { fontSize: '12px', color: '#94a3b8', fontWeight: 600, marginTop: '4px' },

  // Questions section
  qSection: {
    background: '#fff',
    borderRadius: '16px',
    border: '1px solid #f1f5f9',
    boxShadow: '0 1px 4px rgba(0,0,0,0.04)',
    overflow: 'hidden',
  },
  qHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '20px 24px',
    borderBottom: '1px solid #f8fafc',
  },
  qTitle: { fontSize: '15px', fontWeight: 800, color: '#0f172a' },
  addBtn: {
    padding: '9px 18px',
    borderRadius: '9px',
    fontSize: '13px',
    fontWeight: 700,
    background: 'linear-gradient(135deg, #3b82f6, #2563eb)',
    color: '#fff',
    border: 'none',
    cursor: 'pointer',
    fontFamily: FONT,
    boxShadow: '0 2px 8px rgba(59,130,246,0.3)',
  },

  // Question row
  qRow: (i, total) => ({
    display: 'flex',
    alignItems: 'flex-start',
    gap: '16px',
    padding: '18px 24px',
    borderBottom: i < total - 1 ? '1px solid #f8fafc' : 'none',
    transition: 'background 0.15s',
  }),
  qNum: {
    width: '28px',
    height: '28px',
    borderRadius: '8px',
    flexShrink: 0,
    background: '#f1f5f9',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '12px',
    fontWeight: 800,
    color: '#64748b',
    marginTop: '1px',
  },
  qBody: { flex: 1, minWidth: 0 },
  qText: {
    fontSize: '14px',
    fontWeight: 600,
    color: '#0f172a',
    lineHeight: 1.5,
    marginBottom: '8px',
  },
  qMeta: { display: 'flex', gap: '8px', flexWrap: 'wrap', alignItems: 'center' },
  qTag: (bg, color) => ({
    padding: '2px 9px',
    borderRadius: '20px',
    fontSize: '11px',
    fontWeight: 700,
    background: bg,
    color: color,
  }),
  qActions: { display: 'flex', gap: '6px', flexShrink: 0 },
  iconBtn: (color, hoverBg) => ({
    width: '30px',
    height: '30px',
    borderRadius: '7px',
    border: '1px solid #e2e8f0',
    background: '#fff',
    color,
    cursor: 'pointer',
    fontSize: '13px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.15s',
    fontFamily: FONT,
  }),

  // Empty state
  empty: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '64px 32px',
    textAlign: 'center',
  },
  emptyIcon: {
    width: '64px',
    height: '64px',
    borderRadius: '16px',
    background: '#eff6ff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '28px',
    marginBottom: '16px',
  },
  emptyTitle: { fontSize: '16px', fontWeight: 800, color: '#0f172a', marginBottom: '6px' },
  emptyText: { fontSize: '14px', color: '#94a3b8' },

  // Modal overlay
  overlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,0.45)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 999,
    padding: '24px',
  },
  modal: {
    background: '#fff',
    borderRadius: '20px',
    width: '100%',
    maxWidth: '620px',
    maxHeight: '90vh',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: '0 24px 80px rgba(0,0,0,0.25)',
  },
  modalHead: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '22px 28px',
    borderBottom: '1px solid #f1f5f9',
  },
  modalTitle: { fontSize: '17px', fontWeight: 900, color: '#0f172a', letterSpacing: '-0.3px' },
  closeBtn: {
    width: '32px',
    height: '32px',
    borderRadius: '8px',
    border: '1px solid #e2e8f0',
    background: '#f8fafc',
    color: '#64748b',
    cursor: 'pointer',
    fontSize: '16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: FONT,
  },
  modalBody: { padding: '24px 28px', overflowY: 'auto', flex: 1 },
  modalFoot: {
    padding: '18px 28px',
    borderTop: '1px solid #f1f5f9',
    display: 'flex',
    gap: '10px',
    background: '#fafafa',
  },

  // Form elements
  formRow: { marginBottom: '18px' },
  formGrid2: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '14px', marginBottom: '18px' },
  formGrid3: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr 1fr',
    gap: '14px',
    marginBottom: '18px',
  },
  lbl: {
    display: 'block',
    fontSize: '12px',
    fontWeight: 800,
    color: '#374151',
    marginBottom: '6px',
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
  },
  inp: (focused) => ({
    width: '100%',
    padding: '11px 14px',
    fontSize: '14px',
    boxSizing: 'border-box',
    border: `1.5px solid ${focused ? '#3b82f6' : '#e5e7eb'}`,
    borderRadius: '9px',
    outline: 'none',
    color: '#111827',
    background: focused ? '#fff' : '#fafafa',
    boxShadow: focused ? '0 0 0 3px rgba(59,130,246,0.1)' : 'none',
    transition: 'all 0.2s',
    fontFamily: FONT,
  }),
  sel: {
    width: '100%',
    padding: '11px 14px',
    fontSize: '14px',
    boxSizing: 'border-box',
    border: '1.5px solid #e5e7eb',
    borderRadius: '9px',
    outline: 'none',
    color: '#111827',
    background: '#fafafa',
    fontFamily: FONT,
    cursor: 'pointer',
  },
  textarea: (focused) => ({
    width: '100%',
    padding: '11px 14px',
    fontSize: '14px',
    boxSizing: 'border-box',
    border: `1.5px solid ${focused ? '#3b82f6' : '#e5e7eb'}`,
    borderRadius: '9px',
    outline: 'none',
    color: '#111827',
    background: focused ? '#fff' : '#fafafa',
    boxShadow: focused ? '0 0 0 3px rgba(59,130,246,0.1)' : 'none',
    transition: 'all 0.2s',
    fontFamily: FONT,
    resize: 'vertical',
  }),
  divider: { height: '1px', background: '#f1f5f9', margin: '20px 0' },
  sectionLbl: {
    fontSize: '11px',
    fontWeight: 800,
    color: '#94a3b8',
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    marginBottom: '14px',
  },

  optionRow: { display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '10px' },
  optionLetter: {
    width: '28px',
    height: '28px',
    borderRadius: '7px',
    flexShrink: 0,
    background: '#f1f5f9',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '12px',
    fontWeight: 800,
    color: '#64748b',
  },
  radioGroup: { display: 'flex', gap: '10px', flexWrap: 'wrap' },
  radioBtn: (selected) => ({
    padding: '8px 16px',
    borderRadius: '8px',
    fontSize: '13px',
    fontWeight: 600,
    border: `1.5px solid ${selected ? '#3b82f6' : '#e2e8f0'}`,
    background: selected ? '#eff6ff' : '#fafafa',
    color: selected ? '#2563eb' : '#64748b',
    cursor: 'pointer',
    fontFamily: FONT,
    transition: 'all 0.15s',
  }),

  saveBtn: (loading) => ({
    flex: 1,
    padding: '12px',
    fontSize: '14px',
    fontWeight: 700,
    background: loading ? '#93c5fd' : 'linear-gradient(135deg, #3b82f6, #2563eb)',
    color: '#fff',
    border: 'none',
    borderRadius: '10px',
    cursor: loading ? 'not-allowed' : 'pointer',
    fontFamily: FONT,
    boxShadow: loading ? 'none' : '0 2px 8px rgba(59,130,246,0.3)',
  }),
  cancelModalBtn: {
    flex: 1,
    padding: '12px',
    fontSize: '14px',
    fontWeight: 700,
    background: '#fff',
    color: '#64748b',
    border: '1.5px solid #e2e8f0',
    borderRadius: '10px',
    cursor: 'pointer',
    fontFamily: FONT,
  },

  // Type tabs
  typeTabs: { display: 'flex', gap: '6px', flexWrap: 'wrap', marginBottom: '20px' },
  typeTab: (active) => ({
    padding: '7px 14px',
    borderRadius: '8px',
    fontSize: '12px',
    fontWeight: 700,
    border: `1.5px solid ${active ? '#3b82f6' : '#e2e8f0'}`,
    background: active ? '#eff6ff' : '#f8fafc',
    color: active ? '#2563eb' : '#64748b',
    cursor: 'pointer',
    fontFamily: FONT,
    transition: 'all 0.15s',
  }),
};

export const STATUS_STYLES = {
  draft: { bg: '#f1f5f9', color: '#64748b', dot: '#94a3b8' },
  published: { bg: '#f0fdf4', color: '#16a34a', dot: '#22c55e' },
  live: { bg: '#eff6ff', color: '#2563eb', dot: '#3b82f6' },
  completed: { bg: '#faf5ff', color: '#7c3aed', dot: '#8b5cf6' },
};

export const DIFF_STYLES = {
  easy: { bg: '#f0fdf4', color: '#16a34a' },
  medium: { bg: '#fffbeb', color: '#d97706' },
  hard: { bg: '#fef2f2', color: '#dc2626' },
};

export const TYPE_LABELS = {
  mcq: 'MCQ',
  true_false: 'True/False',
  fill_blank: 'Fill Blank',
  descriptive: 'Descriptive',
  coding: 'Coding',
};

export const TYPE_COLORS = {
  mcq: { bg: '#eff6ff', color: '#2563eb' },
  true_false: { bg: '#f0fdf4', color: '#16a34a' },
  fill_blank: { bg: '#fffbeb', color: '#d97706' },
  descriptive: { bg: '#faf5ff', color: '#7c3aed' },
  coding: { bg: '#fff1f2', color: '#e11d48' },
};

export const EMPTY_FORM = {
  question_text: '',
  question_type: 'mcq',
  marks: 1,
  negative_marks: 0,
  difficulty: 'medium',
  subject: '',
  topic: '',
  // MCQ
  option_a: '',
  option_b: '',
  option_c: '',
  option_d: '',
  correct_answer: 'a',
  // T/F
  tf_answer: 'true',
  // Fill blank
  fill_answer: '',
  // Descriptive
  model_answer: '',
  // Coding
  language: 'python',
  starter_code: '',
  expected_output: '',
};
